/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */
/* EcoBridge Economy System - High-Performance Rust Engine */
/* For use with Java 25 Project Panama (Foreign Function API) */

#ifndef ECOBRIDGE_RUST_H
#define ECOBRIDGE_RUST_H

#include <stdint.h>
#include <stdbool.h>

#define DEFAULT_LAMBDA 0.01

#define DEFAULT_TAU 7.0

#define MIN_PHYSICAL_PRICE 0.01

#define DEFAULT_INTEGRATION_LIMIT 30.0

#define MAX_SAFE_DT 1.0

#define MIN_TIME_STEP 1e-6

#define OUTPUT_MIN_CLAMP 0.5

#define OUTPUT_MAX_CLAMP 5.0

#define OUTPUT_BASELINE 1.0

#define INTEGRAL_DECAY 0.99999

#define BACK_CALC_GAIN 0.2

#define DERIVATIVE_FILTER_ALPHA 0.3

#define PANIC_THRESHOLD 50.0

#define PANIC_DAMPING 1.8

#define CODE_NORMAL 0

#define CODE_WARNING_HIGH_RISK 1

#define CODE_BLOCK_REVERSE_FLOW 2

#define CODE_BLOCK_INJECTION 3

#define CODE_BLOCK_INSUFFICIENT_FUNDS 4

/*
 交易定价演算上下文 (48 bytes)
 严格对齐 Java 侧 NativeBridge.Layouts.TRADE_CONTEXT
 */
typedef struct {
  double base_price;
  double current_amount;
  double inflation_rate;
  long long current_timestamp;
  long long play_time_seconds;
  int timezone_offset;
  int newbie_mask;
} TradeContext;

/*
 [关键修复] 市场动态定价配置 (72 bytes)
 已移除 `weights: [f64; 4]` 数组，改为 4 个独立命名字段。
 这消除了 Java FFM 映射时的不确定性。
 */
typedef struct {
  double base_lambda;
  double volatility_factor;
  double seasonal_amplitude;
  double weekend_multiplier;
  double newbie_protection_rate;
  double seasonal_weight;
  double weekend_weight;
  double newbie_weight;
  double inflation_weight;
} MarketConfig;

/*
 工业级 PID 控制器状态 (72 bytes)
 用于动态调节市场税率与平抑异常波动。
 */
typedef struct {
  double kp;
  double ki;
  double kd;
  double lambda;
  double integral;
  double prev_pv;
  double filtered_d;
  double integration_limit;
  int is_saturated;
  /*
   [显式填充]: 确保结构体总大小为 72 字节 (8的倍数)
   */
  int _padding;
} PidState;

/*
 转账演算最终结果 (16 bytes)
 返回给 Java 侧的审计报告。
 */
typedef struct {
  double final_tax;
  int is_blocked;
  int warning_code;
} TransferResult;

/*
 转账风控审计上下文 (56 bytes)
 对应 `ecobridge_compute_transfer_check` 的输入
 */
typedef struct {
  double amount;
  double sender_balance;
  double receiver_balance;
  double inflation_rate;
  double newbie_limit;
  long long sender_play_time;
  long long receiver_play_time;
} TransferContext;

/*
 审计监管与计税配置 (88 bytes)
 */
typedef struct {
  double base_tax_rate;
  double luxury_threshold;
  double luxury_tax_rate;
  double wealth_gap_tax_rate;
  double poor_threshold;
  double rich_threshold;
  double newbie_receive_limit;
  double warning_ratio;
  double warning_min_amount;
  double newbie_hours;
  double veteran_hours;
} RegulatorConfig;

/*
 返回 ABI 版本号 (Hex: 0x00080700 -> v0.8.7)
 v0.8.7 更新：支持人性化非对称定价逻辑 (trade_amount-aware)
 */
uint32_t ecobridge_abi_version(void);

/*
 返回人类可读的版本字符串
 注意：返回的是静态生命周期的字符串指针，Java 侧不应释放它
 */
const char *ecobridge_version(void);

/*
 初始化 DuckDB 连接与异步写入线程
 path_ptr: 数据库文件夹路径 (UTF-8)
 return: 0 成功, 非0 失败
 */
int ecobridge_init_db(const char *path_ptr);

/*
 异步日志写入 (极高频调用)
 该函数设计为 Non-blocking，仅将数据 push 到内存队列
 */
void ecobridge_log_to_duckdb(long long ts,
                             const char *uuid_ptr,
                             double trade_amount,
                             double balance,
                             const char *meta_ptr);

/*
 获取健康状态统计
 out_total: 总接收日志数
 out_dropped: 因队列满而丢弃的日志数 (背压指标)
 */
void ecobridge_get_health_stats(unsigned long long *out_total, unsigned long long *out_dropped);

/*
 向量化有效交易量计算 (Neff)
 从 Read-Only DB 连接中查询
 */
double ecobridge_query_neff_vectorized(long long current_ts, double tau);

/*
 兼容性导出：旧版价格计算入口 (trade_amount 默认为 0)
 */
double ecobridge_compute_price_final(double base, double n_eff, double lambda, double epsilon);

/*
 [v0.8.5 新增] 人性化定价入口
 支持 trade_amount 参数以区分买入/卖出，从而触发“下行粘性”机制
 */
double ecobridge_compute_price_humane(double base,
                                      double n_eff,
                                      double trade_amount,
                                      double lambda,
                                      double epsilon);

/*
 市场环境因子 (Epsilon) 计算 (纯数学)
 [修复] 使用 match 替代 explict return，防止绕过闭包逻辑
 */
double ecobridge_calculate_epsilon(const TradeContext *ctx_ptr, const MarketConfig *cfg_ptr);

/*
 PID 控制器步进计算 (状态机更新)
 已在 internal 实现中增强 D 项阻尼，用于预判恐慌抛售
 */
double ecobridge_compute_pid_adjustment(PidState *pid_ptr,
                                        double target,
                                        double current,
                                        double dt,
                                        double inflation);

/*
 重置 PID 状态
 */
void ecobridge_reset_pid_state(PidState *pid_ptr);

/*
 转账合规性检查
 返回 TransferResult 结构体 (值传递，避免内存分配)
 */
TransferResult ecobridge_compute_transfer_check(const TransferContext *ctx_ptr,
                                                const RegulatorConfig *cfg_ptr);

int ecobridge_shutdown_db(void);

#endif  /* ECOBRIDGE_RUST_H */
