/* Auto-generated by cbindgen - DO NOT EDIT MANUALLY */
/* EcoBridge Economy System - High-Performance Rust Engine */
/* For use with Java 25 Project Panama (Foreign Function API) */

#ifndef ECOBRIDGE_RUST_H
#define ECOBRIDGE_RUST_H

#include <stdint.h>
#include <stdbool.h>

#define DEFAULT_INTEGRATION_LIMIT 30.0

#define MAX_SAFE_DT 1.0

#define MIN_TIME_STEP 1e-6

#define OUTPUT_MIN_CLAMP 0.5

#define OUTPUT_MAX_CLAMP 5.0

#define OUTPUT_BASELINE 1.0

#define INTEGRAL_DECAY 0.99999

#define BACK_CALC_GAIN 0.2

#define DERIVATIVE_FILTER_ALPHA 0.3

#define PANIC_THRESHOLD 50.0

#define PANIC_DAMPING 1.8

#define HEAT_SENSITIVITY 0.5

#define CODE_NORMAL 0

#define CODE_WARNING_HIGH_RISK 1

#define CODE_BLOCK_REVERSE_FLOW 2

#define CODE_BLOCK_INJECTION 3

#define CODE_BLOCK_INSUFFICIENT_FUNDS 4

#define CODE_BLOCK_VELOCITY_LIMIT 5

/*
 交易定价演算上下文 (64 bytes)
 严格对齐 Java 侧 NativeBridge.Layouts.TRADE_CONTEXT
 */
typedef struct {
  double base_price;
  double current_amount;
  double inflation_rate;
  long long current_timestamp;
  long long play_time_seconds;
  int timezone_offset;
  int newbie_mask;
  double market_heat;
  double eco_saturation;
} TradeContext;

/*
 市场动态定价配置 (72 bytes)
 */
typedef struct {
  double base_lambda;
  double volatility_factor;
  double seasonal_amplitude;
  double weekend_multiplier;
  double newbie_protection_rate;
  double seasonal_weight;
  double weekend_weight;
  double newbie_weight;
  double inflation_weight;
} MarketConfig;

/*
 工业级 PID 控制器状态 (72 bytes)
 */
typedef struct {
  double kp;
  double ki;
  double kd;
  double lambda;
  double integral;
  double prev_pv;
  double filtered_d;
  double integration_limit;
  int is_saturated;
  int _padding;
} PidState;

/*
 转账演算最终结果 (16 bytes)
 */
typedef struct {
  double final_tax;
  int is_blocked;
  int warning_code;
} TransferResult;

/*
 转账风控审计上下文 (72 bytes)
 */
typedef struct {
  double amount;
  double sender_balance;
  double receiver_balance;
  double inflation_rate;
  double newbie_limit;
  long long sender_play_time;
  long long receiver_play_time;
  double sender_activity_score;
  int sender_velocity;
  int _padding;
} TransferContext;

/*
 审计监管与计税配置 (96 bytes)
 */
typedef struct {
  double base_tax_rate;
  double luxury_threshold;
  double luxury_tax_rate;
  double wealth_gap_tax_rate;
  double poor_threshold;
  double rich_threshold;
  double newbie_receive_limit;
  double warning_ratio;
  double warning_min_amount;
  double newbie_hours;
  double veteran_hours;
  double velocity_threshold;
} RegulatorConfig;

uint32_t ecobridge_abi_version(void);

const char *ecobridge_version(void);

int ecobridge_init_db(const char *path_ptr);

void ecobridge_log_to_duckdb(long long ts,
                             const char *uuid_ptr,
                             double trade_amount,
                             double balance,
                             const char *meta_ptr);

void ecobridge_get_health_stats(unsigned long long *out_total, unsigned long long *out_dropped);

double ecobridge_query_neff_vectorized(long long current_ts, double tau);

/*
 批量演算价格快照 (SIMD 批处理模式)
 */
void ecobridge_compute_batch_prices(unsigned long long count,
                                    double neff,
                                    const TradeContext *ctx_ptr,
                                    const MarketConfig *cfg_ptr,
                                    const double *hist_avgs_ptr,
                                    const double *lambdas_ptr,
                                    double *results_ptr);

double ecobridge_compute_price_final(double base, double n_eff, double lambda, double epsilon);

double ecobridge_compute_price_humane(double base,
                                      double n_eff,
                                      double trade_amount,
                                      double lambda,
                                      double epsilon);

double ecobridge_compute_price_bounded(double base,
                                       double n_eff,
                                       double amt,
                                       double lambda,
                                       double eps,
                                       double hist_avg);

double ecobridge_compute_tier_price(double base, double qty, bool is_sell);

double ecobridge_calculate_epsilon(const TradeContext *ctx_ptr, const MarketConfig *cfg_ptr);

/*
 演进为自适应宏观调控的 PID 步进接口
 */
double ecobridge_compute_pid_adjustment(PidState *pid_ptr,
                                        double target,
                                        double current,
                                        double dt,
                                        double inflation,
                                        double market_heat);

void ecobridge_reset_pid_state(PidState *pid_ptr);

double ecobridge_calc_inflation(double current_heat, double m1);

double ecobridge_calc_stability(long long last_ts, long long curr_ts);

double ecobridge_calc_decay(double heat, double rate);

void ecobridge_compute_transfer_check(TransferResult *out_result,
                                      const TransferContext *ctx_ptr,
                                      const RegulatorConfig *cfg_ptr);

int ecobridge_shutdown_db(void);

double ecobridge_compute_price_final(double base_price,
                                     double n_eff,
                                     double lambda,
                                     double epsilon);

double ecobridge_compute_price_humane(double base_price,
                                      double n_eff,
                                      double trade_amount,
                                      double lambda,
                                      double epsilon);

double ecobridge_compute_tier_price(double base_price, double quantity, bool is_sell);

double ecobridge_compute_price_bounded(double base,
                                       double neff,
                                       double amt,
                                       double lambda,
                                       double eps,
                                       double hist_avg);

/*
 批量价格演算内核 - 支持并行与 SIMD 加速
 该函数由 FFI 调用，内部使用并行迭代器处理大规模商品定价快照
 */
void ecobridge_compute_batch_prices(uintptr_t count,
                                    double neff,
                                    const TradeContext *ctx_ptr,
                                    const MarketConfig *cfg_ptr,
                                    const double *hist_avgs_ptr,
                                    const double *lambdas_ptr,
                                    double *output_ptr);

#endif  /* ECOBRIDGE_RUST_H */
