name: EcoBridge
version: 2.0.0
main: top.ellan.ecobridge.EcoBridge
api-version: 1.21
authors: [Ellan]
description: "基于 Java 25 FFM + Rust 核心的离散历史求和动态经济系统"

# 强制依赖：缺少任何一个插件，EcoBridge 都不会启动
depend: [CoinsEngine, UltimateShop]

# 加载时机：建议在世界加载后启动，确保 FFI 环境稳定
load: POSTWORLD

commands:
  ecobridge:
    description: "EcoBridge 管理命令"
    usage: "/<command> reload"
    permission: ecobridge.admin
    aliases: [eb, eco]
  
  ecopay:
    description: "发起受监管的 Rust 内核审计转账"
    usage: "/ecopay <player> <amount>"
    permission: ecobridge.pay
    # 注意：如果服务器有 EssentialsX，pay 别名可能会触发冲突
    aliases: [epay, auditpay]

permissions:
  ecobridge.admin:
    description: "允许管理 EcoBridge 原生引擎和重载配置"
    default: op
  
  ecobridge.pay:
    description: "允许玩家使用受监管的转账系统"
    default: true

  # 建议新增：查看经济健康状态的权限
  ecobridge.status:
    description: "允许查看 Rust 引擎的计算状态 (FPS/内存占用)"
    default: op
